#api for creating user account

###
POST http://127.0.0.1:8000/api/signup/
Content-Type: application/json

{
    "username": "raz03",
    "email":"raz@gmail.com",
    "password":"Password@123"  
}

#api for adding new expense
###
POST http://127.0.0.1:8000/api/expenses/
Content-Type: application/json
Authorization: Basic raz03:Password@123

{
    "title":"tour",
    "amount":180,
    "category":"Travel"
}



#api for listing all expenses
###
GET http://127.0.0.1:8000/api/expenses/
Authorization: Basic raz03:Password@123


###
GET http://127.0.0.1:8000/api/expenses/6/
Authorization: Basic raz03:Password@123

#api for updating expense
###
PUT http://127.0.0.1:8000/api/expenses/6/
Content-Type: application/json
Authorization: Basic raz03:Password@123

{
  "id": 6,
  "title":"lunch",
  "amount":190,
  "category":"Food"
  
}



#Api for deleting api
###
DELETE http://127.0.0.1:8000/api/expenses/5/
Authorization: Basic raz03:Password@123

#Api for expense summary

###

GET http://127.0.0.1:8000/api/expenses/summary/
Authorization: Basic raz03:Password@123

